// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-C8lMV6E3yKvLh2PHwVvP78oRsilPj5s',
    appId: '1:688387397041:web:10036367b5f1b08eba1990',
    messagingSenderId: '688387397041',
    projectId: 'padel-app-social',
    authDomain: 'padel-app-social.firebaseapp.com',
    storageBucket: 'padel-app-social.firebasestorage.app',
    measurementId: 'G-XFH9YEKHQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLnXbAsu3cNSCJ1ULJ_aSNbgyPt6Bi8UI',
    appId: '1:688387397041:android:ae0f70ddfee73a24ba1990',
    messagingSenderId: '688387397041',
    projectId: 'padel-app-social',
    storageBucket: 'padel-app-social.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvJydFB5qflALlGTgYHWb0fE9b4rd839A',
    appId: '1:688387397041:ios:513e82948f5739dcba1990',
    messagingSenderId: '688387397041',
    projectId: 'padel-app-social',
    storageBucket: 'padel-app-social.firebasestorage.app',
    iosBundleId: 'com.example.padelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvJydFB5qflALlGTgYHWb0fE9b4rd839A',
    appId: '1:688387397041:ios:513e82948f5739dcba1990',
    messagingSenderId: '688387397041',
    projectId: 'padel-app-social',
    storageBucket: 'padel-app-social.firebasestorage.app',
    iosBundleId: 'com.example.padelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-C8lMV6E3yKvLh2PHwVvP78oRsilPj5s',
    appId: '1:688387397041:web:1c0fd4bdb5862aa7ba1990',
    messagingSenderId: '688387397041',
    projectId: 'padel-app-social',
    authDomain: 'padel-app-social.firebaseapp.com',
    storageBucket: 'padel-app-social.firebasestorage.app',
    measurementId: 'G-HD4QWBGL02',
  );
}
